# This file was generated by GoReleaser. DO NOT EDIT.
cask "rcctl" do
  version "0.17.2"

  on_macos do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "169d1b4e036805d2972678930ad73eeb67c3c15fdf62e7f592943025031e2e6c"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "cb52d95a1c6c52d3bba8d8ef6d308484b9ae00387aca4154d9120c89815f6841"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_amd64.tar.gz"
      sha256 "20233173012e3e44ac92508e1a1440a870b95726bd4b423e6a36415a1d3e4d6f"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_arm64.tar.gz"
      sha256 "bb9f31b728c515084fa5022054b88d335ca49a7b0e5b4df1c2d0d24b6ce4ace9"
    end
  end

  name "rcctl"
  desc "Manage persistent Kubernetes-backed development workspaces for coding agents"
  homepage "https://github.com/nekomeowww/rc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rcctl"

  # No zap stanza required

end
