# This file was generated by GoReleaser. DO NOT EDIT.
cask "rcctl" do
  version "0.15.0"

  on_macos do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "c23621ca57d1312c864d3554eae1520cb313adeef6c677ab7882c68f29e0d45f"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "07459ea66c5b1bf3c570198a4d759c7ec9d1e0e5a27af07d38bdadec3dc4e521"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_amd64.tar.gz"
      sha256 "d34b7f39546b2b00fa2bfdc02ae19b678f88b1d39106f3d37fffd4d83ecedab7"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_arm64.tar.gz"
      sha256 "295c89190f314f6e8f65cf74c87f115c089a835e717c34e1d8aec97347ff990f"
    end
  end

  name "rcctl"
  desc "Manage persistent Kubernetes-backed development workspaces for coding agents"
  homepage "https://github.com/nekomeowww/rc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rcctl"

  # No zap stanza required

end
