# This file was generated by GoReleaser. DO NOT EDIT.
cask "rcctl" do
  version "0.17.0"

  on_macos do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "dd1f726f2568fd1d03da3245e394c410ecb810d899831b79bc8197fbcf0e37ab"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "d11b67a2a9cdacc95ba21f38547febe1836b06c0155c4b83acb303b92745e928"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_amd64.tar.gz"
      sha256 "e04a5afaa58ce0e48cb0f87d26b89cdf8f4d5f4e655de9c792dada376411cee5"
    end
    on_arm do
      url "https://github.com/nekomeowww/rc/releases/download/v#{version}/rcctl_#{version}_linux_arm64.tar.gz"
      sha256 "23110e454c1a5b480f4134c4cae8b446e8d3b5ad6e8297d0c2fdc9da65f63aff"
    end
  end

  name "rcctl"
  desc "Manage persistent Kubernetes-backed development workspaces for coding agents"
  homepage "https://github.com/nekomeowww/rc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rcctl"

  # No zap stanza required

end
